In [27]:
import numpy as np
import pandas as pd
from pandas import ExcelWriter
import os

In [28]:
class Excel_comparison:
    #name = None
    #result_path = None
    
    def __init__(self,Golden_Excel_file,Extracted_Excel_file,result_path):
        self.Golden_Excel_file    = Golden_Excel_file
        self.Extracted_Excel_file = Extracted_Excel_file
        self.result_path = result_path
        self.excel_1 = pd.ExcelFile(self.Golden_Excel_file)    # creaed variables so they can run every time we create object
        self.excel_2 = pd.ExcelFile(self.Extracted_Excel_file)
        self.name = Golden_Excel_file.split('\\')[-1]  # we are getting the name of the current excel file
        
        
    def excel_comparision(self):

        # Create a Pandas Excel writer using XlsxWriter as the engine.
        writer = pd.ExcelWriter(self.result_path +'\\excel_comparison_{}'.format(self.name), engine='xlsxwriter')

        #make the result data frame with shape is equel to df_1.shape
        for sheet in self.excel_1.sheet_names:    #for loop  sheets present innexcel file
            if sheet in self.excel_2.sheet_names:
                df_1 = pd.read_excel(self.excel_1, sheet_name= sheet)
                df_2 = pd.read_excel(self.excel_2, sheet_name= sheet)

                result_df = pd.DataFrame(data = np.NaN, index = df_1.index,columns=df_1.columns)
                for i in df_1.index:
                    for j in df_2.index:
                        # if statement checks the key('Name'+ DOB) of df_1 row with every row in df_2 
                        if (df_1.iloc[i,:2].apply(lambda x:str(x).strip()) ==df_2.iloc[j,:2].apply(lambda x:str(x).strip())).all():
                            #appending the value TRUE, FALSE by checking series of i'th row of df_1 to series of j'th row of df_2
                            result_df.iloc[i,:] = (df_1.iloc[i,:].apply(lambda x:str(x).strip()) == df_2.iloc[j,:].apply(lambda x:str(x).strip())).values
                            break
                        else:
                            result_df.iloc[i,:] = "key not found"
                
            else:
                result_df = pd.DataFrame(data={sheet:"not found in extracted data"})
            result_df.to_excel(writer, sheet_name = sheet)   
        writer.save()

    def excel_Key_comparison(self):

        # Create a Pandas Excel writer using XlsxWriter as the engine.
        writer = pd.ExcelWriter(self.result_path +'\\excel_key_comparison_{}'.format(self.name), engine='xlsxwriter')

        for sheet in self.excel_1.sheet_names: #for loop on number of sheets present innexcel file
            df_1 = pd.read_excel(self.excel_1, sheet_name= sheet)
            df_2 = pd.read_excel(self.excel_2, sheet_name= sheet)


            result2_df = pd.DataFrame(data= df_1, index= df_1.index, columns=df_1.columns[:2])
            result2_df['Number of time key appeared'] = np.zeros(df_1.shape[0])
            for i in df_1.index:
                for j in df_2.index:
                    if (df_1.iloc[i,:2] == df_2.iloc[j,:2]).all(): #this will check key whether present or not
                        result2_df.iloc[i,2] = result2_df.iloc[i,2]+1 #if present it will add to our count

            result2_df.to_excel(writer, sheet_name = sheet)
        writer.save()


    
    def extra_keys(self):

        # Create a Pandas Excel writer using XlsxWriter as the engine.
        writer = pd.ExcelWriter(self.result_path +'\\extra_keys_{}'.format(self.name), engine='xlsxwriter')

        for sheet in self.excel_1.sheet_names: #for loop on number of sheets present innexcel file
            df_1 = pd.read_excel(self.excel_1, sheet_name= sheet)
            df_2 = pd.read_excel(self.excel_2, sheet_name= sheet)


            # not_found_keys are the keys from df_2(extracted) which are not found in df_1(golden data)
            not_found_key = [] #create empty list
            for i in df_2.index:
                for j in df_1.index:
                    if (df_2.iloc[i,:2] == df_1.iloc[j,:2]).all():
                        break
                    else:
                        pass
                else:
                    not_found_key.append(df_2.iloc[i,:2]) #append the not founded key to list

            result3_df= pd.DataFrame(data=not_found_key) #convert list data frame , so we can convert it to excel

            result3_df.to_excel(writer, sheet_name = sheet) #convert data frame to excel, sheetwise

        writer.save()

In [29]:
# here we can put here directory path of golden, extracted and result(where you want to save your results)
golden_data_folder  = r"C:\Users\Shrirang\Desktop\Data Science Practice\My Projects\Mahesh Jupyter notebook\Golden Data"
extracted_data_folder=   r'C:\Users\Shrirang\Desktop\Data Science Practice\My Projects\Mahesh Jupyter notebook\Extracted Data'
result_path         =  r"C:\Users\Shrirang\Desktop\Data Science Practice\My Projects\Mahesh Jupyter notebook\Results"

In [30]:
# get all the excel files in a list
golden_excels = []
extracted_excels = []

for dirname, _, filenames in os.walk(golden_data_folder):
    for filename in filenames:
        golden_excels.append(str(os.path.join(dirname, filename)))
        
for dirname, _, filenames in os.walk(extracted_data_folder):
    for filename in filenames:
        extracted_excels.append(str(os.path.join(dirname, filename)))

In [31]:
for g_path in golden_excels:
    for e_path in extracted_excels:
        if g_path.split('\\')[-1] == e_path.split('\\')[-1]:
            a = Excel_comparison(g_path,e_path,result_path) #class object
            a.excel_Key_comparison()
            a.excel_comparision()
            a.extra_keys()
            break

C:\Users\Shrirang\Anaconda3\lib\site-packages\pandas\io\excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)

In [3]:
golden = pd.ExcelFile(r"C:\Users\Shrirang\Desktop\Data Science Practice\My Projects\Mahesh Jupyter notebook\Golden Data\excel_1.xlsx")
extract = pd.ExcelFile(r"C:\Users\Shrirang\Desktop\Data Science Practice\My Projects\Mahesh Jupyter notebook\Extracted Data\excel_1.xlsx")

In [4]:
golden.sheet_names

['February_20',
 'March_20',
 'Sheet1',
 'April_20',
 'May_20',
 'June_20',
 'July_20',
 'August_20',
 'September_20',
 'October_20',
 'November_20',
 'December_20']

In [5]:
extract.sheet_names

['February_20',
 'March_20',
 'April_20',
 'May_20',
 'June_20',
 'July_20',
 'August_20',
 'September_20',
 'October_20',
 'November_20',
 'December_20']

In [16]:
for sheet in golden.sheet_names:
    if sheet in extract.sheet_names:
        df_1 = pd.read_excel(golden, sheet_name= sheet)
        df_2= pd.read_excel(extract, sheet_name= sheet)
        print(sheet)
    else:
        print('fasle')

February_20
March_20
fasle
April_20
May_20
June_20
July_20
August_20
September_20
October_20
November_20
December_20

In [11]:
df_1

,Name,DOB,12/1,12/2,12/3,12/4,12/5,12/6,12/7,12/8,...,12/18,12/19,12/20,12/21,12/22,12/23,12/24,12/25,12/26,12/27
0,Mahesh,2021-11-01,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
1,Raj,2021-11-02,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
2,Ravi,2021-11-03,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
3,Niki,2021-11-04,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
4,Vaibhav,2021-11-05,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
5,Shyam,2021-11-06,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
6,Shree,2021-11-07,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
7,Sijil,2021-11-08,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
8,Yash,2021-11-09,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR
9,Seema,2021-11-10,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR
10,Rani,2021-11-11,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR
11,Rekha,2021-11-12,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR

In [12]:
df_2

,Name,DOB,12/1,12/2,12/3,12/4,12/5,12/6,12/7,12/8,...,12/18,12/19,12/20,12/21,12/22,12/23,12/24,12/25,12/26,12/27
0,Mahe,2021-11-01,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
1,Raj,2021-11-02,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
2,Ravi,2021-11-03,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
3,Niki,2021-11-04,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
4,Vaibhav,2021-11-05,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
5,Shaym,2021-11-06,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
6,Shree,2021-11-07,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
7,Sijil,2021-11-08,PR,PR,PR,PR,PR,PR,PR,PR,...,AB,PR,PR,PR,PR,PR,PR,PR,PR,PR
8,Yash,2021-11-09,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR
9,Seema,2021-11-10,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR
10,Rani,2021-11-11,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR
11,Rekha,2021-11-12,PR,PR,PR,PR,PR,PR,PR,PR,...,PR,PR,PR,PR,PR,PR,PR,PR,PR,PR